version: "3"

# A custom name of the service/container
# In the below example, we have two containers 
#   - web : Has instructions to build/create/start a node web-app for the environment.
services: 
  
  web:
    build:
      context: "."
      dockerfile: Dockerfile
    
    # <outside world port>:<container port> ==> Map outside world port to container port.
    # We are using redis as production container which listens on port 80
    ports: 
      - "8801:80"

